document.addEventListener("DOMContentLoaded", async () => {
    let marketData = null;
    let portfolio = {
        duration: 'medium',
        credit: 'low',
        energy: 'neutral',
        volatility: 'normal'
    };

    const UI = {
        marketContainer: document.getElementById("market-data-container"),
        actionsContainer: document.getElementById("actions-container"),
        scenarioContainer: document.getElementById("scenario-dashboard"),
        lastUpdated: document.getElementById("last-updated"),
        inputs: {
            duration: document.getElementById("input-duration"),
            credit: document.getElementById("input-credit"),
            energy: document.getElementById("input-energy"),
            volatility: document.getElementById("input-volatility")
        },
        hormuzInput: document.getElementById("input-hormuz")
    };

    // Load Hormuz status from local storage if available
    const savedHormuz = localStorage.getItem("hormuz_status");
    if (savedHormuz) {
        UI.hormuzInput.value = savedHormuz;
    }

    // Initialize Event Listeners for Portfolio Form
    Object.keys(UI.inputs).forEach(key => {
        UI.inputs[key].addEventListener("change", (e) => {
            portfolio[key] = e.target.value;
            if (marketData && marketData.indicators) {
                renderActions(marketData.indicators, portfolio);
            }
        });
    });

    UI.hormuzInput.addEventListener("change", (e) => {
        localStorage.setItem("hormuz_status", e.target.value);
        if (marketData && marketData.indicators) {
            renderScenarios(marketData.indicators);
            renderActions(marketData.indicators, portfolio);
        }
    });

    try {
        // Fetch JSON generated by GitHub Actions
        const response = await fetch("data/data.json");
        if (!response.ok) throw new Error("Data not available");
        marketData = await response.json();

        updateLastUpdated(marketData.timestamp);
        renderMarketData(marketData.indicators, marketData.historical_trends);
        renderScenarios(marketData.indicators);
        renderActions(marketData.indicators, portfolio);
        if (marketData.historical_trends) {
            renderMainChart(marketData.historical_trends);
        }

    } catch (err) {
        console.error("Failed to load market data", err);
        UI.marketContainer.innerHTML = `<div class="p-4 text-red-500 bg-red-50 rounded">暂无法获取实时数据。请检查 GitHub Actions 运行状态。</div>`;
        UI.actionsContainer.innerHTML = `<div class="p-4 text-gray-500">缺少实时数据，无法提供诊断分析。</div>`;
    }

    function updateLastUpdated(timestampStr) {
        if (!timestampStr) return;
        const date = new Date(timestampStr);
        UI.lastUpdated.textContent = "最后更新时间: " + date.toLocaleString("zh-CN", { timeZone: "Asia/Shanghai" });
    }

    function renderMarketData(indicators, historicalTrends) {
        if (!indicators) return;

        const formatters = {
            "VIX": { name: "VIX 恐慌指数", trendKey: "VIX", colorCheck: val => val > 20 ? "text-red-600 bg-red-100" : "text-green-600 bg-green-100" },
            "Brent_Oil": { name: "布伦特原油", trendKey: "Brent_Oil", colorCheck: val => val > 90 ? "text-red-600 bg-red-100" : "text-gray-700 bg-gray-100" },
            "Gold": { name: "黄金价格", trendKey: "Gold", colorCheck: val => val > 2400 ? "text-amber-600 bg-amber-100" : "text-gray-700 bg-gray-100" },
            "USD_Index": { name: "美元指数", trendKey: "USD_Index", colorCheck: val => val > 105 ? "text-blue-600 bg-blue-100" : "text-gray-700 bg-gray-100" },
            "US_10Y_Yield": { name: "美国 10年期名义利率", trendKey: "US_10Y_Yield", colorCheck: val => val > 4.5 ? "text-orange-600 bg-orange-100" : "text-gray-700 bg-gray-100" },
            "TIP_ETF": { name: "TIP ETF (通胀代理)", trendKey: "TIP", colorCheck: val => val > 110 ? "text-indigo-600 bg-indigo-100" : "text-gray-700 bg-gray-100" },
            "SPY_Weekly_Change": { name: "标普500 (周跌幅)", trendKey: "SPY", colorCheck: val => val < -3 ? "text-red-600 bg-red-100" : "text-green-600 bg-green-100" },
            "QQQ_ETF": { name: "纳斯达克 100", trendKey: "QQQ", colorCheck: val => val < 400 ? "text-red-600 bg-red-100" : "text-gray-700 bg-gray-100" },
            "ITA_ETF": { name: "国防军工 ITA", trendKey: "ITA", colorCheck: val => val > 140 ? "text-green-600 bg-green-100" : "text-gray-700 bg-gray-100" },
            "CIBR_ETF": { name: "网络安全 CIBR", trendKey: "CIBR", colorCheck: val => val > 65 ? "text-green-600 bg-green-100" : "text-gray-700 bg-gray-100" },
            "XLP_ETF": { name: "必需消费品 XLP", trendKey: "XLP", colorCheck: val => val < 70 ? "text-red-600 bg-red-100" : "text-gray-700 bg-gray-100" },
            "HYG_Weekly_Change": { name: "高收益债 HYG (周变化)", trendKey: "HYG", colorCheck: val => val < -1 ? "text-red-600 bg-red-100" : "text-gray-700 bg-gray-100" },
            "BTC": { name: "比特币", trendKey: "BTC", colorCheck: val => val < 60000 ? "text-red-600 bg-red-100" : "text-purple-600 bg-purple-100" }
        };

        let html = '<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-1 gap-4">';
        const chartDataMap = {};

        for (const [key, meta] of Object.entries(formatters)) {
            const data = indicators[key];
            if (!data) continue;

            const colorClasses = meta.colorCheck(data.value);
            const chartId = `sparkline-${key}`;

            // For weekly change we might just show the raw SPY/HYG trend in the background
            const histData = historicalTrends && historicalTrends[meta.trendKey] ? historicalTrends[meta.trendKey] : [];
            chartDataMap[chartId] = histData;

            html += `
                <div class="relative overflow-hidden p-4 rounded-xl border border-gray-100 bg-white shadow-sm flex flex-col gap-2">
                    <div class="flex justify-between items-start z-10 relative bg-white">
                        <div>
                            <span class="font-bold text-gray-700 text-sm block">${meta.name}</span>
                            <span class="text-xs text-gray-400">阈值: ${data.threshold}${data.unit}</span>
                        </div>
                        <div class="px-2 py-1 rounded-lg font-bold text-sm ${colorClasses}">
                            ${data.value} ${data.unit}
                        </div>
                    </div>
                    <div class="relative w-full h-8 mt-1 pointer-events-none opacity-40">
                        <canvas id="${chartId}"></canvas>
                    </div>
                </div>
            `;
        }
        html += '</div>';
        UI.marketContainer.innerHTML = html;

        // Render Sparklines
        setTimeout(() => {
            for (const [chartId, dataArray] of Object.entries(chartDataMap)) {
                const ctx = document.getElementById(chartId);
                if (ctx && dataArray.length > 0) {
                    new Chart(ctx, {
                        type: 'line',
                        data: {
                            labels: dataArray.map((_, i) => i),
                            datasets: [{
                                data: dataArray,
                                borderColor: '#3b82f6', // blue-500
                                borderWidth: 2,
                                tension: 0.3,
                                pointRadius: 0
                            }]
                        },
                        options: {
                            responsive: true,
                            maintainAspectRatio: false,
                            plugins: { legend: { display: false }, tooltip: { enabled: false } },
                            scales: { x: { display: false }, y: { display: false } }
                        }
                    });
                }
            }
        }, 100);
    }

    function renderMainChart(historicalTrends) {
        if (!historicalTrends || !historicalTrends.dates || historicalTrends.dates.length === 0) return;

        const ctx = document.getElementById('main-history-chart');
        if (!ctx) return;

        new Chart(ctx, {
            type: 'line',
            data: {
                labels: historicalTrends.dates,
                datasets: [
                    {
                        label: 'VIX 恐慌指数',
                        data: historicalTrends.VIX,
                        borderColor: '#ef4444', // red-500
                        backgroundColor: 'rgba(239, 68, 68, 0.1)',
                        yAxisID: 'y',
                        tension: 0.3
                    },
                    {
                        label: '布伦特原油 ($/bbl)',
                        data: historicalTrends.Brent_Oil,
                        borderColor: '#f59e0b', // amber-500
                        backgroundColor: 'rgba(245, 158, 11, 0.1)',
                        yAxisID: 'y1',
                        tension: 0.3
                    },
                    {
                        label: '标普500',
                        data: historicalTrends.SPY,
                        borderColor: '#3b82f6', // blue-500
                        backgroundColor: 'rgba(59, 130, 246, 0.1)',
                        yAxisID: 'y2',
                        tension: 0.3,
                        hidden: true // hide by default to avoid clutter
                    }
                ]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                layout: {
                    padding: {
                        top: 20
                    }
                },
                plugins: {
                    legend: {
                        labels: {
                            padding: 20
                        }
                    }
                },
                interaction: {
                    mode: 'index',
                    intersect: false,
                },
                scales: {
                    x: {
                        grid: { display: false }
                    },
                    y: {
                        type: 'linear',
                        display: true,
                        position: 'left',
                        title: { display: true, text: 'VIX' },
                        grace: '10%'
                    },
                    y1: {
                        type: 'linear',
                        display: true,
                        position: 'right',
                        title: { display: true, text: 'Oil ($)' },
                        grid: { drawOnChartArea: false },
                        grace: '10%'
                    },
                    y2: {
                        type: 'linear',
                        display: false, // Only visible if dataset is shown
                        position: 'right',
                        grace: '10%'
                    }
                }
            }
        });
    }

    function renderScenarios(indicators) {
        if (!indicators || !UI.scenarioContainer) return;

        const oil = indicators.Brent_Oil?.value || 0;
        const vix = indicators.VIX?.value || 0;
        const hormuz = UI.hormuzInput.value;

        // Basic probability logic based on thresholds
        let probS1S3 = 70; // Default baseline (Noise/Limited)
        let probS4 = 20; // Default baseline (Shipping)
        let probS5 = 10; // Default baseline (Macro Shock)

        if (hormuz === "Warning" || oil > 80) {
            probS1S3 -= 20;
            probS4 += 15;
            probS5 += 5;
        }

        if (hormuz === "Blocked" || oil > 90) {
            probS1S3 = 10;
            probS4 = 60;
            probS5 = 30;
        }

        if (vix > 30 && oil > 100) {
            probS1S3 = 5;
            probS4 = 35;
            probS5 = 60;
        }

        const scenarios = [
            { id: 'S1-S3', name: '噪音 / 局部冲突 (S1-S3)', prob: probS1S3, desc: '航运未实质受损，市场呈短暂避险后修复。', color: 'blue' },
            { id: 'S4', name: '航运扰动 (S4)', prob: probS4, desc: '海峡通行受阻，供应链与保险费飙升。', color: 'orange' },
            { id: 'S5', name: '宏观油价冲击 (S5)', prob: probS5, desc: '油价长期>90，通胀预期去锚，开启滞胀交易。', color: 'red' }
        ];

        let html = '';
        scenarios.forEach(s => {
            const isDominant = s.prob >= 50;
            html += `
                <div class="p-4 rounded-xl border ${isDominant ? `border-${s.color}-500 bg-${s.color}-50 shadow-md` : 'border-gray-200 bg-white opacity-70'} text-center transition-all">
                    <h3 class="font-bold text-gray-800 text-sm mb-1">${s.name}</h3>
                    <div class="text-3xl font-black text-${s.color}-600 mb-2">${s.prob}%</div>
                    <p class="text-xs text-gray-500 leading-tight">${s.desc}</p>
                </div>
            `;
        });
        UI.scenarioContainer.innerHTML = html;
    }

    function renderActions(indicators, currentPortfolio) {
        if (!indicators) return;

        // Extract values
        const vix = indicators.VIX?.value || 0;
        const oil = indicators.Brent_Oil?.value || 0;
        const spyDrop = indicators.SPY_Weekly_Change?.value || 0;
        const hygDrop = indicators.HYG_Weekly_Change?.value || 0; // Negative means stress
        const gold = indicators.Gold?.value || 0;
        const usd = indicators.USD_Index?.value || 0;
        const tip = indicators.TIP_ETF?.value || 0;

        // Check if gold and USD are both high/rising (simple threshold proxy)
        const safeHavenUp = gold > 2400 && usd > 103;
        const tipUp = tip > 108; // threshold proxy

        // Definition of actions from the report
        const actions = [
            {
                id: "rebalance",
                title: "再平衡回到战略权重 (分批)",
                target: "长期投资者；组合偏离目标明显",
                effect: "把“波动”转为纪律化加/减仓",
                triggerCondition: "若VIX > 20 且权益显著下跌",
                triggered: vix > 20 && spyDrop <= -3.0,
                portfolioMatch: currentPortfolio.volatility === "high" || currentPortfolio.volatility === "normal",
                advice: "当前VIX偏高且股市回撤明显，建议按纪律分2-4次回补仓位，避免追逐头条情绪。"
            },
            {
                id: "cash",
                title: "增加短久期美债/现金等价物 (临时缓冲)",
                target: "短期支出/心理承受度低；杠杆风险需降",
                effect: "降低回撤、提升流动性",
                triggerCondition: "油价进入>90区间 或 VIX激增",
                triggered: oil > 90 || vix > 25,
                portfolioMatch: true, // broadly applicable
                advice: "宏观或航运受扰风险急剧上升，建议提升短债与现金缓冲比例以应对跳空下跌。"
            },
            {
                id: "tips",
                title: "增配TIPS (替代部分名义中长债)",
                target: "担心通胀预期上移；持有较多名义久期",
                effect: "对冲通胀预期上行风险",
                triggerCondition: "通胀预期(TIP)上移，或黄金与美元同步走强，或油价>85",
                triggered: oil > 85 || safeHavenUp || tipUp,
                portfolioMatch: currentPortfolio.duration === "high",
                advice: "宏观避险与通胀预期(去锚)信号显现，你持有的长久期名义债承压，建议逐步替换部分为TIPS。"
            },
            {
                id: "energy_hedge",
                title: "小比例能源对冲",
                target: "组合“油价上行净受害”(航空/消费/运输比重大)",
                effect: "对冲油价冲击",
                triggerCondition: "Brent/WTI 出现上行趋势 (当前油价>80)",
                triggered: oil > 80,
                portfolioMatch: currentPortfolio.energy === "vulnerable",
                advice: "你的组合属于油价受害者，建议用小比例(1-5%)购买能源敞口对冲航运扰动尾部风险。"
            },
            {
                id: "option_hedge",
                title: "期权尾部保护 (指数PUT价差/Collar)",
                target: "允许使用期权；担心短期尾部",
                effect: "限定最大亏损、减少强制卖出风险",
                triggerCondition: "VIX 仍在合理区间 (<20) 但事件不确定性高",
                triggered: vix < 20 && oil > 75,
                portfolioMatch: currentPortfolio.volatility === "high" || currentPortfolio.volatility === "normal",
                advice: "当前'保险'依然便宜(VIX不高)，考虑到地缘风险上升，可用小预算购买保护。"
            },
            {
                id: "reduce_hy",
                title: "降低高收益债/高杠杆股票暴露",
                target: "风险偏好下降、信用转弱时",
                effect: "降低违约与利差走阔风险",
                triggerCondition: "VIX > 20 且 信用利差走阔(HYG下跌>1%)",
                triggered: vix > 20 && hygDrop < -1.0,
                portfolioMatch: currentPortfolio.credit === "high",
                advice: "观察到VIX高企且信用市场出现压力，你组合持有较高信用风险敞口，建议降低HY/高杠杆暴露。"
            }
        ];

        let html = '';
        let activeCount = 0;

        actions.forEach(action => {
            const isHighlighted = action.triggered && action.portfolioMatch;
            if (isHighlighted) activeCount++;

            // Render card
            html += `
                <div class="border rounded-xl overflow-hidden transition-all duration-300 ${isHighlighted ? 'border-red-400 shadow-md ring-1 ring-red-400' : 'border-gray-200 bg-gray-50 opacity-80'}">
                    <div class="p-4 ${isHighlighted ? 'bg-red-50' : 'bg-gray-100 border-b border-gray-200'}">
                        <div class="flex items-center justify-between">
                            <h3 class="font-bold text-lg ${isHighlighted ? 'text-red-800' : 'text-gray-700'}">${action.title}</h3>
                            ${isHighlighted ? '<span class="bg-red-500 text-white text-xs px-2 py-1 rounded-full font-semibold animate-pulse">触发建议</span>' : '<span class="text-xs text-gray-500">未触发</span>'}
                        </div>
                        <p class="text-sm text-gray-600 mt-1"><strong>适用：</strong> ${action.target}</p>
                    </div>
                    <div class="p-4 space-y-2 text-sm bg-white">
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                                <span class="text-gray-500 block text-xs">预期效果</span>
                                <span class="text-gray-800">${action.effect}</span>
                            </div>
                            <div>
                                <span class="text-gray-500 block text-xs">触发条件 (if)</span>
                                <span class="text-gray-800">${action.triggerCondition}</span>
                            </div>
                        </div>
                        ${isHighlighted ? `
                            <div class="mt-3 p-3 bg-blue-50 text-blue-800 rounded-lg border border-blue-100 text-sm">
                                <strong>💡 行动建议:</strong> ${action.advice}
                            </div>
                        ` : ''}
                    </div>
                </div>
            `;
        });

        if (activeCount === 0) {
            html = `
                <div class="p-6 text-center bg-green-50 rounded-xl border border-green-200">
                    <svg class="w-12 h-12 text-green-500 mx-auto mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                    <h3 class="text-lg font-bold text-green-800">当前市场情绪平稳，暂无行动建议</h3>
                    <p class="text-green-600 text-sm mt-1">根据实时宏观数据（油价未超阈值，VIX平稳）与您的组合配置，建议保持“纪律性观望”。您可以随时调整左侧配置以预览各种情景。</p>
                </div>
            ` + html;
        }

        UI.actionsContainer.innerHTML = html;
    }
});