document.addEventListener("DOMContentLoaded", async () => {
    let marketData = null;
    let portfolio = {
        duration: 'medium',
        credit: 'low',
        energy: 'neutral',
        volatility: 'normal'
    };

    const UI = {
        marketContainer: document.getElementById("market-data-container"),
        actionsContainer: document.getElementById("actions-container"),
        lastUpdated: document.getElementById("last-updated"),
        inputs: {
            duration: document.getElementById("input-duration"),
            credit: document.getElementById("input-credit"),
            energy: document.getElementById("input-energy"),
            volatility: document.getElementById("input-volatility")
        }
    };

    // Initialize Event Listeners for Portfolio Form
    Object.keys(UI.inputs).forEach(key => {
        UI.inputs[key].addEventListener("change", (e) => {
            portfolio[key] = e.target.value;
            renderActions(marketData, portfolio);
        });
    });

    try {
        // Fetch JSON generated by GitHub Actions
        const response = await fetch("data/data.json");
        if (!response.ok) throw new Error("Data not available");
        marketData = await response.json();

        updateLastUpdated(marketData.timestamp);
        renderMarketData(marketData.indicators);
        renderActions(marketData.indicators, portfolio);

    } catch (err) {
        console.error("Failed to load market data", err);
        UI.marketContainer.innerHTML = `<div class="p-4 text-red-500 bg-red-50 rounded">暂无法获取实时数据。请检查 GitHub Actions 运行状态。</div>`;
        UI.actionsContainer.innerHTML = `<div class="p-4 text-gray-500">缺少实时数据，无法提供诊断分析。</div>`;
    }

    function updateLastUpdated(timestampStr) {
        if (!timestampStr) return;
        const date = new Date(timestampStr);
        UI.lastUpdated.textContent = "最后更新时间: " + date.toLocaleString("zh-CN", { timeZone: "Asia/Shanghai" });
    }

    function renderMarketData(indicators) {
        if (!indicators) return;

        const formatters = {
            "VIX": { name: "VIX 恐慌指数", colorCheck: val => val > 20 ? "text-red-600 bg-red-100" : "text-green-600 bg-green-100" },
            "Brent_Oil": { name: "布伦特原油", colorCheck: val => val > 90 ? "text-red-600 bg-red-100" : "text-gray-700 bg-gray-100" },
            "US_10Y_Yield": { name: "美国 10年期国债收益率", colorCheck: val => val > 4.5 ? "text-orange-600 bg-orange-100" : "text-gray-700 bg-gray-100" },
            "SPY_Weekly_Change": { name: "标普500 (周跌幅)", colorCheck: val => val < -3 ? "text-red-600 bg-red-100" : "text-green-600 bg-green-100" },
            "HYG_Weekly_Change": { name: "高收益债 HYG (周变化)", colorCheck: val => val < -1 ? "text-red-600 bg-red-100" : "text-gray-700 bg-gray-100" }
        };

        let html = '';
        for (const [key, meta] of Object.entries(formatters)) {
            const data = indicators[key];
            if (!data) continue;

            const colorClasses = meta.colorCheck(data.value);

            html += `
                <div class="flex justify-between items-center p-3 rounded-lg border border-gray-100 bg-gray-50">
                    <div>
                        <span class="font-medium text-gray-700 block">${meta.name}</span>
                        <span class="text-xs text-gray-400">预警阈值: ${data.threshold}${data.unit}</span>
                    </div>
                    <div class="px-3 py-1 rounded font-bold ${colorClasses}">
                        ${data.value} ${data.unit}
                    </div>
                </div>
            `;
        }
        UI.marketContainer.innerHTML = html;
    }

    function renderActions(indicators, currentPortfolio) {
        if (!indicators) return;

        // Extract values
        const vix = indicators.VIX.value;
        const oil = indicators.Brent_Oil.value;
        const spyDrop = indicators.SPY_Weekly_Change.value;
        const hygDrop = indicators.HYG_Weekly_Change.value; // Negative means stress

        // Definition of actions from the report
        const actions = [
            {
                id: "rebalance",
                title: "再平衡回到战略权重 (分批)",
                target: "长期投资者；组合偏离目标明显",
                effect: "把“波动”转为纪律化加/减仓",
                triggerCondition: "若VIX > 20 且权益显著下跌",
                triggered: vix > 20 && spyDrop <= -3.0,
                portfolioMatch: currentPortfolio.volatility === "high" || currentPortfolio.volatility === "normal",
                advice: "当前VIX偏高且股市回撤明显，建议按纪律分2-4次回补仓位，避免追逐头条情绪。"
            },
            {
                id: "cash",
                title: "增加短久期美债/现金等价物 (临时缓冲)",
                target: "短期支出/心理承受度低；杠杆风险需降",
                effect: "降低回撤、提升流动性",
                triggerCondition: "油价进入>90区间 或 VIX激增",
                triggered: oil > 90 || vix > 25,
                portfolioMatch: true, // broadly applicable
                advice: "宏观或航运受扰风险急剧上升，建议提升短债与现金缓冲比例以应对跳空下跌。"
            },
            {
                id: "tips",
                title: "增配TIPS (替代部分名义中长债)",
                target: "担心通胀预期上移；持有较多名义久期",
                effect: "对冲通胀预期上行风险",
                triggerCondition: "由于缺乏T10YIE免费数据，使用油价>85作为代理指标",
                triggered: oil > 85,
                portfolioMatch: currentPortfolio.duration === "high",
                advice: "油价持续高位可能导致通胀预期(去锚)上行，你持有的长久期名义债承压，建议逐步替换部分为TIPS。"
            },
            {
                id: "energy_hedge",
                title: "小比例能源对冲",
                target: "组合“油价上行净受害”(航空/消费/运输比重大)",
                effect: "对冲油价冲击",
                triggerCondition: "Brent/WTI 出现上行趋势 (当前油价>80)",
                triggered: oil > 80,
                portfolioMatch: currentPortfolio.energy === "vulnerable",
                advice: "你的组合属于油价受害者，建议用小比例(1-5%)购买能源敞口对冲航运扰动尾部风险。"
            },
            {
                id: "option_hedge",
                title: "期权尾部保护 (指数PUT价差/Collar)",
                target: "允许使用期权；担心短期尾部",
                effect: "限定最大亏损、减少强制卖出风险",
                triggerCondition: "VIX 仍在合理区间 (<20) 但事件不确定性高",
                triggered: vix < 20 && oil > 75,
                portfolioMatch: currentPortfolio.volatility === "high" || currentPortfolio.volatility === "normal",
                advice: "当前'保险'依然便宜(VIX不高)，考虑到地缘风险上升，可用小预算购买保护。"
            },
            {
                id: "reduce_hy",
                title: "降低高收益债/高杠杆股票暴露",
                target: "风险偏好下降、信用转弱时",
                effect: "降低违约与利差走阔风险",
                triggerCondition: "VIX > 20 且 信用利差走阔(HYG下跌>1%)",
                triggered: vix > 20 && hygDrop < -1.0,
                portfolioMatch: currentPortfolio.credit === "high",
                advice: "观察到VIX高企且信用市场出现压力，你组合持有较高信用风险敞口，建议降低HY/高杠杆暴露。"
            }
        ];

        let html = '';
        let activeCount = 0;

        actions.forEach(action => {
            const isHighlighted = action.triggered && action.portfolioMatch;
            if (isHighlighted) activeCount++;

            // Render card
            html += `
                <div class="border rounded-xl overflow-hidden transition-all duration-300 ${isHighlighted ? 'border-red-400 shadow-md ring-1 ring-red-400' : 'border-gray-200 bg-gray-50 opacity-80'}">
                    <div class="p-4 ${isHighlighted ? 'bg-red-50' : 'bg-gray-100 border-b border-gray-200'}">
                        <div class="flex items-center justify-between">
                            <h3 class="font-bold text-lg ${isHighlighted ? 'text-red-800' : 'text-gray-700'}">${action.title}</h3>
                            ${isHighlighted ? '<span class="bg-red-500 text-white text-xs px-2 py-1 rounded-full font-semibold animate-pulse">触发建议</span>' : '<span class="text-xs text-gray-500">未触发</span>'}
                        </div>
                        <p class="text-sm text-gray-600 mt-1"><strong>适用：</strong> ${action.target}</p>
                    </div>
                    <div class="p-4 space-y-2 text-sm bg-white">
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                                <span class="text-gray-500 block text-xs">预期效果</span>
                                <span class="text-gray-800">${action.effect}</span>
                            </div>
                            <div>
                                <span class="text-gray-500 block text-xs">触发条件 (if)</span>
                                <span class="text-gray-800">${action.triggerCondition}</span>
                            </div>
                        </div>
                        ${isHighlighted ? `
                            <div class="mt-3 p-3 bg-blue-50 text-blue-800 rounded-lg border border-blue-100 text-sm">
                                <strong>💡 行动建议:</strong> ${action.advice}
                            </div>
                        ` : ''}
                    </div>
                </div>
            `;
        });

        if (activeCount === 0) {
            html = `
                <div class="p-6 text-center bg-green-50 rounded-xl border border-green-200">
                    <svg class="w-12 h-12 text-green-500 mx-auto mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                    <h3 class="text-lg font-bold text-green-800">当前市场情绪平稳，暂无行动建议</h3>
                    <p class="text-green-600 text-sm mt-1">根据实时宏观数据（油价未超阈值，VIX平稳）与您的组合配置，建议保持“纪律性观望”。您可以随时调整左侧配置以预览各种情景。</p>
                </div>
            ` + html;
        }

        UI.actionsContainer.innerHTML = html;
    }
});